### PR TITLE
migrate to null safety

### PR DESCRIPTION
**Pull request by elmissouri16**

### CODE REVIEW

**Comment by yiss** [comment]
Thank you so much for this. I was trying to find some time to do it! Did you test it does it work?

**Comment by elmissouri16** [comment]
> Thank you so much for this. I was trying to find some time to do it! Did you test it does it work?

Still not yet fully but we can leave it pending until I can confirm I have app depending on this package and it's not yet fully migrated  but I think it's should work fine since they are not much logic on the package I just update the SDK version and package that's depending on it

**Comment by VictorUvarov** [comment]
You should also move the `recase` dependency to `dev_dependencies` as it is only needed by the tool.

**Comment by elmissouri16** [comment]
> You should also move the `recase` dependency to `dev_dependencies` as it is only needed by the tool.

Yeah true I just did changes based on the author previous work to not break , but yeah I agree with that's should be the case

**Comment by yiss** [comment]
Great! Once you confirm there is no breaking change I'll merge it. @elmissouri16 can you also please add the modification suggested by @VictorUvarov thank you! 😃 I should also think to add a reference to all the icons in the Readme

**Comment by elmissouri16** [comment]
> Great! Once you confirm there is no breaking change I'll merge it. @elmissouri16 can you also please add the modification suggested by @VictorUvarov thank you! 😃 I should also think to add a reference to all the icons in the Readme

Yeah sure thing I will do it once I test it

**Comment by VictorUvarov** [comment]
I'm using the fork and all the icons seem to work. This package had nothing to migrate.

**Comment by elmissouri16** [comment]
> I'm using the fork and all the icons seem to work. This package had nothing to migrate.

Yeah they are almost nothing but still just to follow flutter guidelines and keep it updated with new changes and remove the warnings

**Comment by elmissouri16** [comment]
@yiss i think its good to go

**Comment by yiss** [comment]
@elmissouri16 awesome thank you!

**Pull request merged**
